web/router.ex
defmodule Forum.Router do
  use Forum.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Forum.Auth, repo: Forum.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Forum do
    pipe_through [:browser] # Use the default browser stack

    get "/", PostController, :index, as: :home
    resources "/posts", PostController do
      resources "/comments", CommentController, only: [:create, :delete, :edit, :update]
    end
    get "/login", SessionController, :new, as: :login
    post "/login", SessionController, :create, as: :login
    delete "/logout", SessionController, :delete, as: :logout
    get "/register", UserController, :new, as: :register
    post "/register", UserController, :create, as: :register
  end

  # Other scopes may use custom stacks.
  # scope "/api", Forum do
  #   pipe_through :api
  # end
end

web/models/post.ex
defmodule Forum.Post do
  use Forum.Web, :model

  schema "posts" do
    field :title, :string
    field :content, :string
    belongs_to :user, Forum.User
    has_many :comments, Forum.Comment

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title, :content])
    |> validate_required([:title, :content])
  end
end

web/controllers/post_controller.ex
defmodule Forum.PostController do
  use Forum.Web, :controller

  import Ecto.Query

  alias Forum.{Post, Comment}

  plug :authenticate_user when action in [:new, :create, :edit, :delete]

  def index(conn, params) do
    posts =
    	Post
        |> order_by(desc: :inserted_at)
        |> preload(:user)
        |> Repo.paginate(params)
    render conn, "index.html", posts: posts
  end

  def show(conn, %{"id" => id}) do
    comment_query = from c in Comment,
                    order_by: [desc: c.inserted_at],
                    preload: :user

    post_query = from p in Post,
                 where: p.id == ^id,
                 preload: [comments: ^comment_query]

    post = Repo.one(post_query)

    comment_changeset = Comment.changeset(%Comment{})
    render(conn, "show.html", post: post, comment_changeset: comment_changeset)
  end

  def new(conn, _params) do
    changeset = Post.changeset(%Post{})
    render conn, "new.html", changeset: changeset
  end

  def create(conn, %{"post" => post_params}) do
    changeset =
      conn.assigns.current_user
        |> build_assoc(:posts)
        |> Post.changeset(post_params)

    case Repo.insert(changeset) do
      {:ok, post} ->
        conn
          |> put_flash(:info, "Post created successfully!")
          |> redirect(to: post_path(conn, :show, post))
      {:error, changeset} ->
        conn
          |> put_flash(:error, "Oops something wen't wrong! Please check the errors below")
          |> render("new.html", changeset: changeset)
    end
  end

  def edit(conn, %{"id" => id}) do
    post = Repo.get(Post, id)
    changeset = Post.changeset(post)
    render conn, "edit.html", changeset: changeset, post: post
  end

  def update(conn, %{"id" => id, "post" => post_params}) do
    post = Repo.get(Post, id)
    changeset = Post.changeset(post, post_params)

    case Repo.update(changeset) do
      {:ok, post} ->
        conn
          |> put_flash(:info, "Post updated successfully!")
          |> redirect(to: post_path(conn, :show, post))

      {:error, changeset} ->
        render conn, "edit.html", changeset: changeset
    end
  end

  def delete(conn, %{"id" => id}) do
    post = Repo.get(Post, id)
    if(post.user_id == conn.assigns.current_user.id) do
      Repo.delete!(post)

      conn
        |> put_flash(:info, "Post deleted successfully!")
        |> redirect(to: post_path(conn, :index))
    else
      conn
        |> put_flash(:error, "Unauthorized!")
        |> redirect(to: post_path(conn, :show, post))
    end
    
  end
end

web/views/post_view.ex
defmodule Forum.PostView do
  use Forum.Web, :view
  import Scrivener.HTML

  def time_ago_in_words(ecto_datetime) do
    {:ok, date} =  Ecto.DateTime.dump(ecto_datetime)
    
    date
      |> Timex.DateTime.from()
      |> Timex.from_now
  end
end

web/templates/post/edit.html.eex
<%= render "form.html", changeset: @changeset, action: post_path(@conn, :update, @post) %>
<%= link "Back", to: post_path(@conn, :show, @post) %>

web/templates/post/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= label f, :title, "Title:" %>
  <%= text_input f, :title %>
  <%= error_tag f, :title %>

  <%= label f, :content, "Content:" %>
  <%= textarea f, :content %>
  <%= error_tag f, :content %>

  <%= submit "Submit" %>
<% end %>

web/templates/post/index.html.eex
<div id="posts">
  <%= for post <- @posts do %>
  <div class="post">
    <h2 class="title"><%= link post.title, to: post_path(@conn, :show, post) %></h2>
    <p class="date">Published <%= time_ago_in_words(post.inserted_at) %> by <%= post.user.name %></p>
  </div>
<% end %>
  <div class="align-center">
    <%= pagination_links @conn, @posts, next: "»", previous: "«", first: true, last: true, view_style: :bootstrap %>
  </div>
</div>

web/templates/post/new.html.eex
<div class="white-background">
  <h1>New Post</h1>
  <%= render "form.html", changeset: @changeset, action: post_path(@conn, :create) %>
</div>

web/templates/post/show.html.eex
<div id="post_content_content">
  <h1><%= @post.title %></h1>
  <p><%= @post.content %></p>
  <div id="comments">
    <h2><%= Enum.count(@post.comments) %> Comments</h2>
    <%= for comment <- @post.comments do %>
      <%= if @current_user do  %>
        <%= render Forum.CommentView, "comment.html", comment: comment, conn: @conn, post: @post, current_user_id: @current_user.id %>
      <% else %>
        <%= render Forum.CommentView, "comment.html", comment: comment, conn: @conn, post: @post, current_user_id: nil %>
      <% end %>
    <% end %>
    <%= if @current_user do  %>
      <%= render Forum.CommentView, "form.html", changeset: @comment_changeset, action: post_comment_path(@conn, :create, @post) %>
    <% end %>
  </div>

  <%= if @current_user do %>
    <%= if @post.user_id == @current_user.id do %>
      <br>
      <hr>
      <br>
      <div class="manage-buttons">
        <%= link "Edit", to: post_path(@conn, :edit, @post), class: "button" %>
        <%= link "Delete", to: post_path(@conn, :delete, @post), method: :delete, data: [confirm: "Are you sure?"], class: "button" %>
      </div>
    <% end %>
  <% end %>
  
</div>