web/router.ex
defmodule Forum.Router do
  use Forum.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Forum.Auth, repo: Forum.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Forum do
    pipe_through [:browser] # Use the default browser stack

    get "/", PostController, :index, as: :home
    resources "/posts", PostController do
      resources "/comments", CommentController, only: [:create, :delete, :edit, :update]
    end
    get "/login", SessionController, :new, as: :login
    post "/login", SessionController, :create, as: :login
    delete "/logout", SessionController, :delete, as: :logout
    get "/register", UserController, :new, as: :register
    post "/register", UserController, :create, as: :register
  end

  # Other scopes may use custom stacks.
  # scope "/api", Forum do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Forum.LayoutView do
  use Forum.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Simple Phoenix Forum</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/normalize/4.1.1/normalize.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <header class="main_header clearfix">
      <div class="wrapper">
        <div id="logo"><p><%= link "Simple Phoenix Forum", to: home_path(@conn, :index) %></p></div>
        <div id="buttons">
          <%= if @current_user do %>
            <%= link "New Post", to: post_path(@conn, :new), class: "new-post-button" %>
            <%= link "Logout", to: logout_path(@conn, :delete), method: :delete, class: "logout-button" %>
          <% else %>
            <%= link "Register", to: register_path(@conn, :new) %>
            <%= link "Login", to: login_path(@conn, :new) %>
          <% end %>
        </div>
      </div>
    </header>

    
    <div class="wrapper">
      <%= if get_flash(@conn, :info) || get_flash(@conn, :error) do %>
        <%= if get_flash(@conn, :info) do %>
          <p class="alert alert-info" role="alert"><%= String.capitalize(get_flash(@conn, :info)) %></p>
        <% end %>
        <%= if get_flash(@conn, :error) do %>
          <p class="alert alert-danger" role="alert"><%= String.capitalize(get_flash(@conn, :error)) %></p>
        <% end %>
      <% else %>
        <p></p>
        <p></p>
      <% end %>
    </div>
    
    <div class="wrapper">
      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>
    </div>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>